query getActiveChannel {
  activeChannel {
    id
    defaultCurrencyCode
    seller {
      id
      name

      customFields {
        siteTitle
        logo {
          source
          preview
        }
      }
    }
  }
}
